### ISSUE TITLE
Problem installing from source

### ISSUE THREAD

**Issue by jean** [getgauge-contrib/gauge-js#13] opened 2016-01-15 18:42 UTC
```
01:36 john@UX303LB:~/repos/git/gauge-js(master)$ npm run installPlugin
> gauge-js@0.1.1 installPlugin /home/john/repos/git/gauge-js
> node ./scripts/install.js

Installed gauge-js v0.1.1
```

However this doesn't seem to result in a usable plugin:

```
01:37 john@UX303LB:~/tmp/gauge-js$ gauge --init js
[INFO] Compatible js plugin is not installed
[INFO] Installing plugin => js ...
[CRITICAL] Failed to initialize. Failed to install plugin js . Invalid plugin : Could not download js-install.json file. File does not exist. 

01:38 john@UX303LB:~/tmp/gauge-js$ ls ~/.gauge/plugins/js/
0.1.1
```

**Comment by renjithgr** [comment] 2016-01-15 21:19
What is the version of Gauge installed in that machine?

**Comment by kaustavdm** [comment] 2016-01-16 05:06
@jean We had raise minimum gauge version to v0.3.0. You will need to install Gauge 0.3.0 for js runner to work.

The second issue about `Invalid plugin` is because the `js` plugin is not part of gauge's hosted plugin list yet. It should be in sometime because of getgauge/gauge-repository#3.

@renjithgr Need to specify this in docs.

**Comment by kaustavdm** [comment] 2016-01-28 07:07
Closing this as I cannot reproduce this with the latest stable Gauge and JS runner plugin.

**Closed by kaustavdm** 2016-01-28 07:07 UTC
